# data parameters
dataset_name: celeba                         # used for saving csv. Easy to remember which dataset you're evalulating, especially, if you're using multiple datasets.
dataset_with_subfolders: False               # True
dataset_format: image                        # file_list # file_list is not implemented. I will implement it later. Easier to implement.
multiple_evaluation: True
generated_image_path: /media/la-belva/E/LAB_ALL/LAB_Inpainting_CelebA/test_results_ablation_attention_mechanism/output
ground_truth_image_path: /media/la-belva/2681c8e6-6bc0-4b9f-9dba-22ade6dedc89/home/la_belva/PycharmProjects/Comparison_values/celeba_random_150
return_dataset_name: False                   # Currently, no use. In future, it will be used for multi-testing.


# experiment
exp_type: ablation
model_name: difnet

# processing parameters
batch_size: 4                                # set according to your GPU/CPU
image_shape: [ 256, 256, 3 ]                 # set according to your need.
random_crop: False                           # currently, not implemented. In future, it will be used to evaluate patches.
threads: 4                                   # set according to your CPU.

# print option
print_interval_frequency: 1
show_config: False

# save options
save_results: True
save_results_path: /home/la-belva/Research_Ground/DIFNET_ACCESS/Results/logs/ablation/attention
save_file_name: metrics
save_type: csv